# This is a basic workflow to help you get started with Actions

name: ML Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run_full_workflow"
  run_full_workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Debugging with tmate
    #   uses: mxschmitt/action-tmate@v2

    - name: Setup Environment
      id: setup_environment
      run: |
        python3 -m pip install -U setuptools wheel pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install flake8
        python3 -m pip install ipython
        python3 -m pip install jupyter 
        python3 -m pip install nbconvert

    - name: Lint checked in code files
      id: python_linting
      run: |
        python3 -m flake8 src --count --config=.flake8 --show-source --statistics

    - name: Convert Notebook to Script
      id: convert_notebook_to_script
      run: |
        python3 -m nbconvert notebooks/production/*.ipynb --config notebooks/nbconvert_config.py
        cp notebooks/production/*.py src/train
        cp notebooks/production/*.json src/train
        cp notebooks/production/*.hdf5 src/train

    - name: Run Unit Tests
      id: python_unit_tests
      run: |
        python3 -m unittest discover -s src -p 'test_*.py'

    - name: MLSpec Action - Process Data
      uses: mlspec/mlspeclib-action-docker@0.1.0
      with:
        METASTORE_CREDENTIALS: ${{ secrets.METASTORE_CREDENTIALS_PROD }}
        WORKFLOW_NODE_ID: 'workflow|500.0.1|17141130-b02d-4472-9146-74e8c01c724d'
        STEP_NAME: process_data
        SCHEMAS_DIRECTORY: .parameters/schemas
        SCHEMAS_GIT_URL: https://github.com/mlspec/mlspeclib-action-samples-schemas.git
        NEXT_STEP_NAME: train
        INPUT_PARAMETERS_FILE_PATH: ${{ github.workspace }}/.parameters/process_data/input.yaml
        EXECUTION_PARAMETERS_FILE_PATH: ${{ github.workspace }}/.parameters/process_data/execution.yaml
        EXECUTION_FILE: ${{ github.workspace }}/src/process_data/process_data.py

    - name: MLSpec Action - Train
      uses: mlspec/mlspeclib-action-docker@0.1.0
      with:
        METASTORE_CREDENTIALS: ${{ secrets.METASTORE_CREDENTIALS_PROD }}
        WORKFLOW_NODE_ID: 'workflow|500.0.1|17141130-b02d-4472-9146-74e8c01c724d'
        STEP_NAME: process_data
        SCHEMAS_DIRECTORY: .parameters/schemas
        SCHEMAS_GIT_URL: https://github.com/mlspec/mlspeclib-action-samples-schemas.git
        NEXT_STEP_NAME: train
        INPUT_PARAMETERS_FILE_PATH: ${{ github.workspace }}/.parameters/process_data/input.yaml
        EXECUTION_PARAMETERS_FILE_PATH: ${{ github.workspace }}/.parameters/process_data/execution.yaml
        EXECUTION_FILE: ${{ github.workspace }}/src/train/train.py

    - name: MLSpec Action - Package
      uses: mlspec/mlspeclib-action-docker@0.1.0
      with:
        METASTORE_CREDENTIALS: ${{ secrets.METASTORE_CREDENTIALS_PROD }}
        WORKFLOW_NODE_ID: 'workflow|500.0.1|17141130-b02d-4472-9146-74e8c01c724d'
        STEP_NAME: process_data
        SCHEMAS_DIRECTORY: .parameters/schemas
        SCHEMAS_GIT_URL: https://github.com/mlspec/mlspeclib-action-samples-schemas.git
        NEXT_STEP_NAME: train
        INPUT_PARAMETERS_FILE_PATH: ${{ github.workspace }}/.parameters/process_data/input.yaml
        EXECUTION_PARAMETERS_FILE_PATH: ${{ github.workspace }}/.parameters/process_data/execution.yaml
        EXECUTION_FILE: ${{ github.workspace }}/src/package.py

