schema_version: 500.0.1
nodes: 10
cpu_per_node: 4
ram_per_node: 64Gi
gpu_required: true
output_path: models/output
training_params:
    learning_rate: 0.001
    loss: 0.1923
    batch_size: 2000
    epoch: 50
    optimizer: ['SGD']
    train_op: minimize
    other_tags:
        pii: false
        data_sha: 8b03f70
schema_type: training_run
base_image: ubuntu1804
machine_type: NDv2
        
